// Generated by gencpp from file multi_apriltags_tracker/april_tag_pos.msg
// DO NOT EDIT!


#ifndef MULTI_APRILTAGS_TRACKER_MESSAGE_APRIL_TAG_POS_H
#define MULTI_APRILTAGS_TRACKER_MESSAGE_APRIL_TAG_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace multi_apriltags_tracker
{
template <class ContainerAllocator>
struct april_tag_pos_
{
  typedef april_tag_pos_<ContainerAllocator> Type;

  april_tag_pos_()
    : id()
    , pose()  {
    }
  april_tag_pos_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , pose(_alloc)  {
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _id_type;
  _id_type id;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> const> ConstPtr;

}; // struct april_tag_pos_

typedef ::multi_apriltags_tracker::april_tag_pos_<std::allocator<void> > april_tag_pos;

typedef boost::shared_ptr< ::multi_apriltags_tracker::april_tag_pos > april_tag_posPtr;
typedef boost::shared_ptr< ::multi_apriltags_tracker::april_tag_pos const> april_tag_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multi_apriltags_tracker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'multi_apriltags_tracker': ['/home/theta/catkin_ws/src/multi_apriltags_tracker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d940b52850c16cf09dbca2e129664c5";
  }

  static const char* value(const ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d940b52850c16cfULL;
  static const uint64_t static_value2 = 0x09dbca2e129664c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_apriltags_tracker/april_tag_pos";
  }

  static const char* value(const ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] id\n\
geometry_msgs/Pose2D[] pose \n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct april_tag_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_apriltags_tracker::april_tag_pos_<ContainerAllocator>& v)
  {
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_APRILTAGS_TRACKER_MESSAGE_APRIL_TAG_POS_H
