(cl:defpackage apriltags_intrude_detector-srv
  (:use )
  (:export
   "APRILTAGS_INTRUDE"
   "<APRILTAGS_INTRUDE-REQUEST>"
   "APRILTAGS_INTRUDE-REQUEST"
   "<APRILTAGS_INTRUDE-RESPONSE>"
   "APRILTAGS_INTRUDE-RESPONSE"
   "APRILTAGS_INFO"
   "<APRILTAGS_INFO-REQUEST>"
   "APRILTAGS_INFO-REQUEST"
   "<APRILTAGS_INFO-RESPONSE>"
   "APRILTAGS_INFO-RESPONSE"
  ))

