// Generated by gencpp from file sphero_swarm_node/SpheroHeading.msg
// DO NOT EDIT!


#ifndef SPHERO_SWARM_NODE_MESSAGE_SPHEROHEADING_H
#define SPHERO_SWARM_NODE_MESSAGE_SPHEROHEADING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sphero_swarm_node
{
template <class ContainerAllocator>
struct SpheroHeading_
{
  typedef SpheroHeading_<ContainerAllocator> Type;

  SpheroHeading_()
    : name()
    , heading(0.0)  {
    }
  SpheroHeading_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , heading(0.0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _heading_type;
  _heading_type heading;




  typedef boost::shared_ptr< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> const> ConstPtr;

}; // struct SpheroHeading_

typedef ::sphero_swarm_node::SpheroHeading_<std::allocator<void> > SpheroHeading;

typedef boost::shared_ptr< ::sphero_swarm_node::SpheroHeading > SpheroHeadingPtr;
typedef boost::shared_ptr< ::sphero_swarm_node::SpheroHeading const> SpheroHeadingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sphero_swarm_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'sphero_swarm_node': ['/home/theta/catkin_ws/src/sphero_ros/sphero_swarm_node/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4e9b156f6244799b2f2da71f9b5a530";
  }

  static const char* value(const ::sphero_swarm_node::SpheroHeading_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4e9b156f6244799ULL;
  static const uint64_t static_value2 = 0xb2f2da71f9b5a530ULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_swarm_node/SpheroHeading";
  }

  static const char* value(const ::sphero_swarm_node::SpheroHeading_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float32 heading\n\
";
  }

  static const char* value(const ::sphero_swarm_node::SpheroHeading_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SpheroHeading_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_swarm_node::SpheroHeading_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sphero_swarm_node::SpheroHeading_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_SWARM_NODE_MESSAGE_SPHEROHEADING_H
