// Generated by gencpp from file sphero_swarm_node/SpheroInfoRequest.msg
// DO NOT EDIT!


#ifndef SPHERO_SWARM_NODE_MESSAGE_SPHEROINFOREQUEST_H
#define SPHERO_SWARM_NODE_MESSAGE_SPHEROINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sphero_swarm_node
{
template <class ContainerAllocator>
struct SpheroInfoRequest_
{
  typedef SpheroInfoRequest_<ContainerAllocator> Type;

  SpheroInfoRequest_()
    : name()
    , bt_addr()  {
    }
  SpheroInfoRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , bt_addr(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _bt_addr_type;
  _bt_addr_type bt_addr;




  typedef boost::shared_ptr< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpheroInfoRequest_

typedef ::sphero_swarm_node::SpheroInfoRequest_<std::allocator<void> > SpheroInfoRequest;

typedef boost::shared_ptr< ::sphero_swarm_node::SpheroInfoRequest > SpheroInfoRequestPtr;
typedef boost::shared_ptr< ::sphero_swarm_node::SpheroInfoRequest const> SpheroInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sphero_swarm_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'sphero_swarm_node': ['/home/theta/catkin_ws/src/sphero_ros/sphero_swarm_node/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad6df3775fe4208c7a2bfb8e29c25e1d";
  }

  static const char* value(const ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad6df3775fe4208cULL;
  static const uint64_t static_value2 = 0x7a2bfb8e29c25e1dULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_swarm_node/SpheroInfoRequest";
  }

  static const char* value(const ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string bt_addr\n\
";
  }

  static const char* value(const ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.bt_addr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SpheroInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sphero_swarm_node::SpheroInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "bt_addr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.bt_addr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_SWARM_NODE_MESSAGE_SPHEROINFOREQUEST_H
