// Generated by gencpp from file sphero_swarm_node/SpheroBackLed.msg
// DO NOT EDIT!


#ifndef SPHERO_SWARM_NODE_MESSAGE_SPHEROBACKLED_H
#define SPHERO_SWARM_NODE_MESSAGE_SPHEROBACKLED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sphero_swarm_node
{
template <class ContainerAllocator>
struct SpheroBackLed_
{
  typedef SpheroBackLed_<ContainerAllocator> Type;

  SpheroBackLed_()
    : name()
    , back_led(0.0)  {
    }
  SpheroBackLed_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , back_led(0.0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _back_led_type;
  _back_led_type back_led;




  typedef boost::shared_ptr< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> const> ConstPtr;

}; // struct SpheroBackLed_

typedef ::sphero_swarm_node::SpheroBackLed_<std::allocator<void> > SpheroBackLed;

typedef boost::shared_ptr< ::sphero_swarm_node::SpheroBackLed > SpheroBackLedPtr;
typedef boost::shared_ptr< ::sphero_swarm_node::SpheroBackLed const> SpheroBackLedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sphero_swarm_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'sphero_swarm_node': ['/home/theta/catkin_ws/src/sphero_ros/sphero_swarm_node/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d427143c65efd6f97ef90d6e139b367c";
  }

  static const char* value(const ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd427143c65efd6f9ULL;
  static const uint64_t static_value2 = 0x7ef90d6e139b367cULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_swarm_node/SpheroBackLed";
  }

  static const char* value(const ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float32 back_led\n\
";
  }

  static const char* value(const ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.back_led);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SpheroBackLed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sphero_swarm_node::SpheroBackLed_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "back_led: ";
    Printer<float>::stream(s, indent + "  ", v.back_led);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_SWARM_NODE_MESSAGE_SPHEROBACKLED_H
