// Generated by gencpp from file apriltags_intrude_detector/apriltags_intrude.msg
// DO NOT EDIT!


#ifndef APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INTRUDE_H
#define APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INTRUDE_H

#include <ros/service_traits.h>


#include <apriltags_intrude_detector/apriltags_intrudeRequest.h>
#include <apriltags_intrude_detector/apriltags_intrudeResponse.h>


namespace apriltags_intrude_detector
{

struct apriltags_intrude
{

typedef apriltags_intrudeRequest Request;
typedef apriltags_intrudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct apriltags_intrude
} // namespace apriltags_intrude_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_intrude > {
  static const char* value()
  {
    return "443a09552f8457c3ab7679cc90f2c84e";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_intrude&) { return value(); }
};

template<>
struct DataType< ::apriltags_intrude_detector::apriltags_intrude > {
  static const char* value()
  {
    return "apriltags_intrude_detector/apriltags_intrude";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_intrude&) { return value(); }
};


// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_intrudeRequest> should match 
// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_intrude > 
template<>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_intrudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apriltags_intrude_detector::apriltags_intrude >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_intrudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltags_intrude_detector::apriltags_intrudeRequest> should match 
// service_traits::DataType< ::apriltags_intrude_detector::apriltags_intrude > 
template<>
struct DataType< ::apriltags_intrude_detector::apriltags_intrudeRequest>
{
  static const char* value()
  {
    return DataType< ::apriltags_intrude_detector::apriltags_intrude >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_intrudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_intrudeResponse> should match 
// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_intrude > 
template<>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_intrudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apriltags_intrude_detector::apriltags_intrude >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_intrudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltags_intrude_detector::apriltags_intrudeResponse> should match 
// service_traits::DataType< ::apriltags_intrude_detector::apriltags_intrude > 
template<>
struct DataType< ::apriltags_intrude_detector::apriltags_intrudeResponse>
{
  static const char* value()
  {
    return DataType< ::apriltags_intrude_detector::apriltags_intrude >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_intrudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INTRUDE_H
