// Generated by gencpp from file apriltags_intrude_detector/apriltags_intrudeRequest.msg
// DO NOT EDIT!


#ifndef APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INTRUDEREQUEST_H
#define APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INTRUDEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apriltags_intrude_detector
{
template <class ContainerAllocator>
struct apriltags_intrudeRequest_
{
  typedef apriltags_intrudeRequest_<ContainerAllocator> Type;

  apriltags_intrudeRequest_()
    : x(0.0)
    , y(0.0)  {
    }
  apriltags_intrudeRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct apriltags_intrudeRequest_

typedef ::apriltags_intrude_detector::apriltags_intrudeRequest_<std::allocator<void> > apriltags_intrudeRequest;

typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_intrudeRequest > apriltags_intrudeRequestPtr;
typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_intrudeRequest const> apriltags_intrudeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apriltags_intrude_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff8d7d66dd3e4b73ULL;
  static const uint64_t static_value2 = 0x1ef14a45d38888b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apriltags_intrude_detector/apriltags_intrudeRequest";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct apriltags_intrudeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apriltags_intrude_detector::apriltags_intrudeRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INTRUDEREQUEST_H
