// Generated by gencpp from file apriltags_intrude_detector/apriltags_infoRequest.msg
// DO NOT EDIT!


#ifndef APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INFOREQUEST_H
#define APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apriltags_intrude_detector
{
template <class ContainerAllocator>
struct apriltags_infoRequest_
{
  typedef apriltags_infoRequest_<ContainerAllocator> Type;

  apriltags_infoRequest_()
    {
    }
  apriltags_infoRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct apriltags_infoRequest_

typedef ::apriltags_intrude_detector::apriltags_infoRequest_<std::allocator<void> > apriltags_infoRequest;

typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_infoRequest > apriltags_infoRequestPtr;
typedef boost::shared_ptr< ::apriltags_intrude_detector::apriltags_infoRequest const> apriltags_infoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apriltags_intrude_detector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apriltags_intrude_detector/apriltags_infoRequest";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct apriltags_infoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::apriltags_intrude_detector::apriltags_infoRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INFOREQUEST_H
