// Generated by gencpp from file apriltags_intrude_detector/apriltags_info.msg
// DO NOT EDIT!


#ifndef APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INFO_H
#define APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INFO_H

#include <ros/service_traits.h>


#include <apriltags_intrude_detector/apriltags_infoRequest.h>
#include <apriltags_intrude_detector/apriltags_infoResponse.h>


namespace apriltags_intrude_detector
{

struct apriltags_info
{

typedef apriltags_infoRequest Request;
typedef apriltags_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct apriltags_info
} // namespace apriltags_intrude_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_info > {
  static const char* value()
  {
    return "1c6a00f14d4c3b3ffcd440f6c4b8a029";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_info&) { return value(); }
};

template<>
struct DataType< ::apriltags_intrude_detector::apriltags_info > {
  static const char* value()
  {
    return "apriltags_intrude_detector/apriltags_info";
  }

  static const char* value(const ::apriltags_intrude_detector::apriltags_info&) { return value(); }
};


// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_infoRequest> should match 
// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_info > 
template<>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apriltags_intrude_detector::apriltags_info >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltags_intrude_detector::apriltags_infoRequest> should match 
// service_traits::DataType< ::apriltags_intrude_detector::apriltags_info > 
template<>
struct DataType< ::apriltags_intrude_detector::apriltags_infoRequest>
{
  static const char* value()
  {
    return DataType< ::apriltags_intrude_detector::apriltags_info >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_infoResponse> should match 
// service_traits::MD5Sum< ::apriltags_intrude_detector::apriltags_info > 
template<>
struct MD5Sum< ::apriltags_intrude_detector::apriltags_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apriltags_intrude_detector::apriltags_info >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltags_intrude_detector::apriltags_infoResponse> should match 
// service_traits::DataType< ::apriltags_intrude_detector::apriltags_info > 
template<>
struct DataType< ::apriltags_intrude_detector::apriltags_infoResponse>
{
  static const char* value()
  {
    return DataType< ::apriltags_intrude_detector::apriltags_info >::value();
  }
  static const char* value(const ::apriltags_intrude_detector::apriltags_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APRILTAGS_INTRUDE_DETECTOR_MESSAGE_APRILTAGS_INFO_H
